export const POST_NOTIFICATION = "POST_NOTIFICATION";
export const MESSAGE_NOTIFICATION = "MESSAGE_NOTIFICATION";
export const INCOMING_NOTIFICATION = "INCOMING_NOTIFICATION";
export const INCOMING_MESSAGE = "INCOMING_MESSAGE";
export const CLIENT_COUNT_NOTIFICATION = "CLIENT_COUNT_NOTIFICATION";
export const ANONYMOUS = "Anonymous";